zero  = lambda s=None: eval(f'0 {s}') if s else '0'
one   = lambda s=None: eval(f'1 {s}') if s else '1'
two   = lambda s=None: eval(f'2 {s}') if s else '2'
three = lambda s=None: eval(f'3 {s}') if s else '3'
four  = lambda s=None: eval(f'4 {s}') if s else '4'
five  = lambda s=None: eval(f'5 {s}') if s else '5'
six   = lambda s=None: eval(f'6 {s}') if s else '6'
seven = lambda s=None: eval(f'7 {s}') if s else '7'
eight = lambda s=None: eval(f'8 {s}') if s else '8'
nine  = lambda s=None: eval(f'9 {s}') if s else '9'

plus       = lambda n: f'+ {n}'
minus      = lambda n: f'- {n}'
times      = lambda n: f'* {n}'
divided_by = lambda n: f'//{n}'
